docs:
  script:
    - set -ev
    - export PKG_VERSION="0.0.3"
    - GROUP=$(basename $(dirname $CI_BUILD_REPO))
    - PROJECT=$(basename $CI_BUILD_REPO)
    - PROJECT=${PROJECT%.*}
    - OUTPUT_DIR="/var/www/docs/$GROUP/$PROJECT" 
    - export PATH=/home/kimadmin/anaconda/envs/gitlab-docs/bin:$PATH
    - rm -rf "$OUTPUT_DIR"
    - mkdir -p "$OUTPUT_DIR"
    - python -m biodb build_docs --input_dir "./docs" --output_dir "$OUTPUT_DIR"

