create index a on chemical_interactions_v2.biogrid_topo (ensp_1, ensp_2) ;
create index a on chemical_interactions_v2.biogrid_topo_eb (ensp_1, ensp_2);
create index a on chemical_interactions_v2.biogrid_topo_nsp (ensp_1, ensp_2);
create index a on chemical_interactions_v2.gene_coexpression (ensp_1, ensp_2);
create index a on chemical_interactions_v2.gene_essentiality (ensp);
create index a on chemical_interactions_v2.getint_topo (ensp_1, ensp_2);
create index a on chemical_interactions_v2.getint_topo_eb (ensp_1, ensp_2);
create index a on chemical_interactions_v2.getint_topo_nsp (ensp_1, ensp_2);
create index a on chemical_interactions_v2.go_all (ensp_1, ensp_2);
create index a on chemical_interactions_v2.go_bp (ensp_1, ensp_2);
create index a on chemical_interactions_v2.go_cc (ensp_1, ensp_2);
create index a on chemical_interactions_v2.go_mf (ensp_1, ensp_2);
create index a on chemical_interactions_v2.go_slim (ensp_1, ensp_2);
create index a on chemical_interactions_v2.phylo (ensp_1, ensp_2);
create index a on chemical_interactions_v2.string_topo (ensp_1, ensp_2);
create index a on chemical_interactions_v2.string_topo_eb (ensp_1, ensp_2);
create index a on chemical_interactions_v2.string_topo_nsp (ensp_1, ensp_2);
