-- This file is not used anymore.

DROP TABLE IF EXISTS machine_learning_validation;

CREATE TABLE machine_learning_validation AS
SELECT

# ap
ap.*,

# ap_gbdpp
ap_gbdpp.synergy_score_1_gbdpp,
ap_gbdpp.synergy_score_diff_gbdpp,
ap_gbdpp.max_conc_mean_mean_gbdpp,
ap_gbdpp.max_conc_mean_diff_gbdpp,
ap_gbdpp.max_conc_diff_mean_gbdpp,
ap_gbdpp.max_conc_diff_diff_gbdpp,
ap_gbdpp.ic50_mean_mean_gbdpp,
ap_gbdpp.ic50_mean_diff_gbdpp,
ap_gbdpp.ic50_diff_mean_gbdpp,
ap_gbdpp.ic50_diff_diff_gbdpp,
ap_gbdpp.h_mean_mean_gbdpp,
ap_gbdpp.h_mean_diff_gbdpp,
ap_gbdpp.h_diff_mean_gbdpp,
ap_gbdpp.h_diff_diff_gbdpp,
ap_gbdpp.einf_mean_mean_gbdpp,
ap_gbdpp.einf_mean_diff_gbdpp,
ap_gbdpp.einf_diff_mean_gbdpp,
ap_gbdpp.einf_diff_diff_gbdpp,

# ap_gbdcl
ap_gbdcl.synergy_score_1_gbclp,
ap_gbdcl.synergy_score_diff_gbclp,
ap_gbdcl.max_conc_mean_mean_gbclp,
ap_gbdcl.max_conc_mean_diff_gbclp,
ap_gbdcl.max_conc_diff_mean_gbclp,
ap_gbdcl.max_conc_diff_diff_gbclp,
ap_gbdcl.ic50_mean_mean_gbclp,
ap_gbdcl.ic50_mean_diff_gbclp,
ap_gbdcl.ic50_diff_mean_gbclp,
ap_gbdcl.ic50_diff_diff_gbclp,
ap_gbdcl.h_mean_mean_gbclp,
ap_gbdcl.h_mean_diff_gbclp,
ap_gbdcl.h_diff_mean_gbclp,
ap_gbdcl.h_diff_diff_gbclp,
ap_gbdcl.einf_mean_mean_gbclp,
ap_gbdcl.einf_mean_diff_gbclp,
ap_gbdcl.einf_diff_mean_gbclp,
ap_gbdcl.einf_diff_diff_gbclp,


# 1
# a_gbdp_avg
(a_gbdp_2.synergy_score + a_gbdp_1.synergy_score) / 2 a_gbdp_avg_synergy_score,
(a_gbdp_2.COUNT + a_gbdp_1.COUNT) / 2 a_gbdp_avg_COUNT,
(a_gbdp_2.max_conc_mean + a_gbdp_1.max_conc_mean) / 2 a_gbdp_avg_max_conc_mean,
(a_gbdp_2.max_conc_diff + a_gbdp_1.max_conc_diff) / 2 a_gbdp_avg_max_conc_diff,
(a_gbdp_2.ic50_mean + a_gbdp_1.ic50_mean) / 2 a_gbdp_avg_ic50_mean,
(a_gbdp_2.ic50_diff + a_gbdp_1.ic50_diff) / 2 a_gbdp_avg_ic50_diff,
(a_gbdp_2.h_mean + a_gbdp_1.h_mean) / 2 a_gbdp_avg_h_mean,
(a_gbdp_2.h_diff + a_gbdp_1.h_diff) / 2 a_gbdp_avg_h_diff,
(a_gbdp_2.einf_mean + a_gbdp_1.einf_mean) / 2 a_gbdp_avg_einf_mean,
(a_gbdp_2.einf_diff + a_gbdp_1.einf_diff) / 2 a_gbdp_avg_einf_diff,
# a_gbdp_diff
(a_gbdp_2.synergy_score - a_gbdp_1.synergy_score) a_gbdp_diff_synergy_score,
(a_gbdp_2.COUNT - a_gbdp_1.COUNT) a_gbdp_diff_COUNT,
(a_gbdp_2.max_conc_mean - a_gbdp_1.max_conc_mean) a_gbdp_diff_max_conc_mean,
(a_gbdp_2.max_conc_diff - a_gbdp_1.max_conc_diff) a_gbdp_diff_max_conc_diff,
(a_gbdp_2.ic50_mean - a_gbdp_1.ic50_mean) a_gbdp_diff_ic50_mean,
(a_gbdp_2.ic50_diff - a_gbdp_1.ic50_diff) a_gbdp_diff_ic50_diff,
(a_gbdp_2.h_mean - a_gbdp_1.h_mean) a_gbdp_diff_h_mean,
(a_gbdp_2.h_diff - a_gbdp_1.h_diff) a_gbdp_diff_h_diff,
(a_gbdp_2.einf_mean - a_gbdp_1.einf_mean) a_gbdp_diff_einf_mean,
(a_gbdp_2.einf_diff - a_gbdp_1.einf_diff) a_gbdp_diff_einf_diff,

# 2
# a_gbcl_avg
(a_gbcl_2.MAX_CONC_mean + a_gbcl_1.MAX_CONC_mean) / 2 a_gbcl_avg_MAX_CONC_mean,
(a_gbcl_2.MAX_CONC_std + a_gbcl_1.MAX_CONC_std) / 2 a_gbcl_avg_MAX_CONC_std,
(a_gbcl_2.IC50_mean + a_gbcl_1.IC50_mean) / 2 a_gbcl_avg_IC50_mean,
(a_gbcl_2.IC50_std + a_gbcl_1.IC50_std) / 2 a_gbcl_avg_IC50_std,
(a_gbcl_2.H_mean + a_gbcl_1.H_mean) / 2 a_gbcl_avg_H_mean,
(a_gbcl_2.H_std + a_gbcl_1.H_std) / 2 a_gbcl_avg_H_std,
(a_gbcl_2.Einf_mean + a_gbcl_1.Einf_mean) / 2 a_gbcl_avg_Einf_mean,
(a_gbcl_2.Einf_std + a_gbcl_1.Einf_std) / 2 a_gbcl_avg_Einf_std,
(a_gbcl_2.COUNT + a_gbcl_1.COUNT) / 2 a_gbcl_avg_COUNT,
# a_gbcl_diff
(a_gbcl_2.MAX_CONC_mean - a_gbcl_1.MAX_CONC_mean) a_gbcl_diff_MAX_CONC_mean,
(a_gbcl_2.MAX_CONC_std - a_gbcl_1.MAX_CONC_std) a_gbcl_diff_MAX_CONC_std,
(a_gbcl_2.IC50_mean - a_gbcl_1.IC50_mean) a_gbcl_diff_IC50_mean,
(a_gbcl_2.IC50_std - a_gbcl_1.IC50_std) a_gbcl_diff_IC50_std,
(a_gbcl_2.H_mean - a_gbcl_1.H_mean) a_gbcl_diff_H_mean,
(a_gbcl_2.H_std - a_gbcl_1.H_std) a_gbcl_diff_H_std,
(a_gbcl_2.Einf_mean - a_gbcl_1.Einf_mean) a_gbcl_diff_Einf_mean,
(a_gbcl_2.Einf_std - a_gbcl_1.Einf_std) a_gbcl_diff_Einf_std,
(a_gbcl_2.COUNT - a_gbcl_1.COUNT) a_gbcl_diff_COUNT,

# 3
# clare_avg_avg
(clare_avg_2.bg_degree + clare_avg_1.bg_degree) / 2 clare_avg_avg_bg_degree,
(clare_avg_2.bg_clustering_coef + clare_avg_1.bg_clustering_coef) / 2 clare_avg_avg_bg_clustering_coef,
(clare_avg_2.bg_betweenness + clare_avg_1.bg_betweenness) / 2 clare_avg_avg_bg_betweenness,
(clare_avg_2.bg_closeness + clare_avg_1.bg_closeness) / 2 clare_avg_avg_bg_closeness,
(clare_avg_2.bg_neighbor_sharing + clare_avg_1.bg_neighbor_sharing) / 2 clare_avg_avg_bg_neighbor_sharing,
(clare_avg_2.bg_shortest_path_length + clare_avg_1.bg_shortest_path_length) / 2 clare_avg_avg_bg_shortest_path_length,
(clare_avg_2.bg_eb_max + clare_avg_1.bg_eb_max) / 2 clare_avg_avg_bg_eb_max,
(clare_avg_2.bg_eb_min + clare_avg_1.bg_eb_min) / 2 clare_avg_avg_bg_eb_min,
(clare_avg_2.bg_eb_mean + clare_avg_1.bg_eb_mean) / 2 clare_avg_avg_bg_eb_mean,
(clare_avg_2.bg_eb_fraction + clare_avg_1.bg_eb_fraction) / 2 clare_avg_avg_bg_eb_fraction,
(clare_avg_2.bg_number_of_shortest_paths + clare_avg_1.bg_number_of_shortest_paths) / 2 clare_avg_avg_bg_number_of_shortest_paths,
(clare_avg_2.coexpression + clare_avg_1.coexpression) / 2 clare_avg_avg_coexpression,
(clare_avg_2.gi_degree + clare_avg_1.gi_degree) / 2 clare_avg_avg_gi_degree,
(clare_avg_2.gi_clustering_coef + clare_avg_1.gi_clustering_coef) / 2 clare_avg_avg_gi_clustering_coef,
(clare_avg_2.gi_betweenness + clare_avg_1.gi_betweenness) / 2 clare_avg_avg_gi_betweenness,
(clare_avg_2.gi_closeness + clare_avg_1.gi_closeness) / 2 clare_avg_avg_gi_closeness,
(clare_avg_2.gi_neighbor_sharing + clare_avg_1.gi_neighbor_sharing) / 2 clare_avg_avg_gi_neighbor_sharing,
(clare_avg_2.gi_shortest_path_length + clare_avg_1.gi_shortest_path_length) / 2 clare_avg_avg_gi_shortest_path_length,
(clare_avg_2.gi_eb_max + clare_avg_1.gi_eb_max) / 2 clare_avg_avg_gi_eb_max,
(clare_avg_2.gi_eb_min + clare_avg_1.gi_eb_min) / 2 clare_avg_avg_gi_eb_min,
(clare_avg_2.gi_eb_mean + clare_avg_1.gi_eb_mean) / 2 clare_avg_avg_gi_eb_mean,
(clare_avg_2.gi_eb_fraction + clare_avg_1.gi_eb_fraction) / 2 clare_avg_avg_gi_eb_fraction,
(clare_avg_2.gi_number_of_shortest_paths + clare_avg_1.gi_number_of_shortest_paths) / 2 clare_avg_avg_gi_number_of_shortest_paths,
(clare_avg_2.go_all_sem_sim + clare_avg_1.go_all_sem_sim) / 2 clare_avg_avg_go_all_sem_sim,
(clare_avg_2.go_bp_sem_sim + clare_avg_1.go_bp_sem_sim) / 2 clare_avg_avg_go_bp_sem_sim,
(clare_avg_2.go_cc_sem_sim + clare_avg_1.go_cc_sem_sim) / 2 clare_avg_avg_go_cc_sem_sim,
(clare_avg_2.go_mf_sem_sim + clare_avg_1.go_mf_sem_sim) / 2 clare_avg_avg_go_mf_sem_sim,
(clare_avg_2.go_slim_sem_sim + clare_avg_1.go_slim_sem_sim) / 2 clare_avg_avg_go_slim_sem_sim,
(clare_avg_2.phylogenic_similarity + clare_avg_1.phylogenic_similarity) / 2 clare_avg_avg_phylogenic_similarity,
(clare_avg_2.s_degree + clare_avg_1.s_degree) / 2 clare_avg_avg_s_degree,
(clare_avg_2.s_clustering_coef + clare_avg_1.s_clustering_coef) / 2 clare_avg_avg_s_clustering_coef,
(clare_avg_2.s_betweenness + clare_avg_1.s_betweenness) / 2 clare_avg_avg_s_betweenness,
(clare_avg_2.s_closeness + clare_avg_1.s_closeness) / 2 clare_avg_avg_s_closeness,
(clare_avg_2.s_neighbor_sharing + clare_avg_1.s_neighbor_sharing) / 2 clare_avg_avg_s_neighbor_sharing,
(clare_avg_2.s_shortest_path_length + clare_avg_1.s_shortest_path_length) / 2 clare_avg_avg_s_shortest_path_length,
(clare_avg_2.s_eb_max + clare_avg_1.s_eb_max) / 2 clare_avg_avg_s_eb_max,
(clare_avg_2.s_eb_min + clare_avg_1.s_eb_min) / 2 clare_avg_avg_s_eb_min,
(clare_avg_2.s_eb_mean + clare_avg_1.s_eb_mean) / 2 clare_avg_avg_s_eb_mean,
(clare_avg_2.s_eb_fraction + clare_avg_1.s_eb_fraction) / 2 clare_avg_avg_s_eb_fraction,
(clare_avg_2.s_number_of_shortest_paths + clare_avg_1.s_number_of_shortest_paths) / 2 clare_avg_avg_s_number_of_shortest_paths,
# clare_avg_diff
(clare_avg_2.bg_degree - clare_avg_1.bg_degree) clare_avg_diff_bg_degree,
(clare_avg_2.bg_clustering_coef - clare_avg_1.bg_clustering_coef) clare_avg_diff_bg_clustering_coef,
(clare_avg_2.bg_betweenness - clare_avg_1.bg_betweenness) clare_avg_diff_bg_betweenness,
(clare_avg_2.bg_closeness - clare_avg_1.bg_closeness) clare_avg_diff_bg_closeness,
(clare_avg_2.bg_neighbor_sharing - clare_avg_1.bg_neighbor_sharing) clare_avg_diff_bg_neighbor_sharing,
(clare_avg_2.bg_shortest_path_length - clare_avg_1.bg_shortest_path_length) clare_avg_diff_bg_shortest_path_length,
(clare_avg_2.bg_eb_max - clare_avg_1.bg_eb_max) clare_avg_diff_bg_eb_max,
(clare_avg_2.bg_eb_min - clare_avg_1.bg_eb_min) clare_avg_diff_bg_eb_min,
(clare_avg_2.bg_eb_mean - clare_avg_1.bg_eb_mean) clare_avg_diff_bg_eb_mean,
(clare_avg_2.bg_eb_fraction - clare_avg_1.bg_eb_fraction) clare_avg_diff_bg_eb_fraction,
(clare_avg_2.bg_number_of_shortest_paths - clare_avg_1.bg_number_of_shortest_paths) clare_avg_diff_bg_number_of_shortest_paths,
(clare_avg_2.coexpression - clare_avg_1.coexpression) clare_avg_diff_coexpression,
(clare_avg_2.gi_degree - clare_avg_1.gi_degree) clare_avg_diff_gi_degree,
(clare_avg_2.gi_clustering_coef - clare_avg_1.gi_clustering_coef) clare_avg_diff_gi_clustering_coef,
(clare_avg_2.gi_betweenness - clare_avg_1.gi_betweenness) clare_avg_diff_gi_betweenness,
(clare_avg_2.gi_closeness - clare_avg_1.gi_closeness) clare_avg_diff_gi_closeness,
(clare_avg_2.gi_neighbor_sharing - clare_avg_1.gi_neighbor_sharing) clare_avg_diff_gi_neighbor_sharing,
(clare_avg_2.gi_shortest_path_length - clare_avg_1.gi_shortest_path_length) clare_avg_diff_gi_shortest_path_length,
(clare_avg_2.gi_eb_max - clare_avg_1.gi_eb_max) clare_avg_diff_gi_eb_max,
(clare_avg_2.gi_eb_min - clare_avg_1.gi_eb_min) clare_avg_diff_gi_eb_min,
(clare_avg_2.gi_eb_mean - clare_avg_1.gi_eb_mean) clare_avg_diff_gi_eb_mean,
(clare_avg_2.gi_eb_fraction - clare_avg_1.gi_eb_fraction) clare_avg_diff_gi_eb_fraction,
(clare_avg_2.gi_number_of_shortest_paths - clare_avg_1.gi_number_of_shortest_paths) clare_avg_diff_gi_number_of_shortest_paths,
(clare_avg_2.go_all_sem_sim - clare_avg_1.go_all_sem_sim) clare_avg_diff_go_all_sem_sim,
(clare_avg_2.go_bp_sem_sim - clare_avg_1.go_bp_sem_sim) clare_avg_diff_go_bp_sem_sim,
(clare_avg_2.go_cc_sem_sim - clare_avg_1.go_cc_sem_sim) clare_avg_diff_go_cc_sem_sim,
(clare_avg_2.go_mf_sem_sim - clare_avg_1.go_mf_sem_sim) clare_avg_diff_go_mf_sem_sim,
(clare_avg_2.go_slim_sem_sim - clare_avg_1.go_slim_sem_sim) clare_avg_diff_go_slim_sem_sim,
(clare_avg_2.phylogenic_similarity - clare_avg_1.phylogenic_similarity) clare_avg_diff_phylogenic_similarity,
(clare_avg_2.s_degree - clare_avg_1.s_degree) clare_avg_diff_s_degree,
(clare_avg_2.s_clustering_coef - clare_avg_1.s_clustering_coef) clare_avg_diff_s_clustering_coef,
(clare_avg_2.s_betweenness - clare_avg_1.s_betweenness) clare_avg_diff_s_betweenness,
(clare_avg_2.s_closeness - clare_avg_1.s_closeness) clare_avg_diff_s_closeness,
(clare_avg_2.s_neighbor_sharing - clare_avg_1.s_neighbor_sharing) clare_avg_diff_s_neighbor_sharing,
(clare_avg_2.s_shortest_path_length - clare_avg_1.s_shortest_path_length) clare_avg_diff_s_shortest_path_length,
(clare_avg_2.s_eb_max - clare_avg_1.s_eb_max) clare_avg_diff_s_eb_max,
(clare_avg_2.s_eb_min - clare_avg_1.s_eb_min) clare_avg_diff_s_eb_min,
(clare_avg_2.s_eb_mean - clare_avg_1.s_eb_mean) clare_avg_diff_s_eb_mean,
(clare_avg_2.s_eb_fraction - clare_avg_1.s_eb_fraction) clare_avg_diff_s_eb_fraction,
(clare_avg_2.s_number_of_shortest_paths - clare_avg_1.s_number_of_shortest_paths) clare_avg_diff_s_number_of_shortest_paths,

# 4
# clare_max_avg
(clare_max_2.bg_degree + clare_max_1.bg_degree) / 2 clare_max_avg_bg_degree,
(clare_max_2.bg_clustering_coef + clare_max_1.bg_clustering_coef) / 2 clare_max_avg_bg_clustering_coef,
(clare_max_2.bg_betweenness + clare_max_1.bg_betweenness) / 2 clare_max_avg_bg_betweenness,
(clare_max_2.bg_closeness + clare_max_1.bg_closeness) / 2 clare_max_avg_bg_closeness,
(clare_max_2.bg_neighbor_sharing + clare_max_1.bg_neighbor_sharing) / 2 clare_max_avg_bg_neighbor_sharing,
(clare_max_2.bg_shortest_path_length + clare_max_1.bg_shortest_path_length) / 2 clare_max_avg_bg_shortest_path_length,
(clare_max_2.bg_eb_max + clare_max_1.bg_eb_max) / 2 clare_max_avg_bg_eb_max,
(clare_max_2.bg_eb_min + clare_max_1.bg_eb_min) / 2 clare_max_avg_bg_eb_min,
(clare_max_2.bg_eb_mean + clare_max_1.bg_eb_mean) / 2 clare_max_avg_bg_eb_mean,
(clare_max_2.bg_eb_fraction + clare_max_1.bg_eb_fraction) / 2 clare_max_avg_bg_eb_fraction,
(clare_max_2.bg_number_of_shortest_paths + clare_max_1.bg_number_of_shortest_paths) / 2 clare_max_avg_bg_number_of_shortest_paths,
(clare_max_2.coexpression + clare_max_1.coexpression) / 2 clare_max_avg_coexpression,
(clare_max_2.gi_degree + clare_max_1.gi_degree) / 2 clare_max_avg_gi_degree,
(clare_max_2.gi_clustering_coef + clare_max_1.gi_clustering_coef) / 2 clare_max_avg_gi_clustering_coef,
(clare_max_2.gi_betweenness + clare_max_1.gi_betweenness) / 2 clare_max_avg_gi_betweenness,
(clare_max_2.gi_closeness + clare_max_1.gi_closeness) / 2 clare_max_avg_gi_closeness,
(clare_max_2.gi_neighbor_sharing + clare_max_1.gi_neighbor_sharing) / 2 clare_max_avg_gi_neighbor_sharing,
(clare_max_2.gi_shortest_path_length + clare_max_1.gi_shortest_path_length) / 2 clare_max_avg_gi_shortest_path_length,
(clare_max_2.gi_eb_max + clare_max_1.gi_eb_max) / 2 clare_max_avg_gi_eb_max,
(clare_max_2.gi_eb_min + clare_max_1.gi_eb_min) / 2 clare_max_avg_gi_eb_min,
(clare_max_2.gi_eb_mean + clare_max_1.gi_eb_mean) / 2 clare_max_avg_gi_eb_mean,
(clare_max_2.gi_eb_fraction + clare_max_1.gi_eb_fraction) / 2 clare_max_avg_gi_eb_fraction,
(clare_max_2.gi_number_of_shortest_paths + clare_max_1.gi_number_of_shortest_paths) / 2 clare_max_avg_gi_number_of_shortest_paths,
(clare_max_2.go_all_sem_sim + clare_max_1.go_all_sem_sim) / 2 clare_max_avg_go_all_sem_sim,
(clare_max_2.go_bp_sem_sim + clare_max_1.go_bp_sem_sim) / 2 clare_max_avg_go_bp_sem_sim,
(clare_max_2.go_cc_sem_sim + clare_max_1.go_cc_sem_sim) / 2 clare_max_avg_go_cc_sem_sim,
(clare_max_2.go_mf_sem_sim + clare_max_1.go_mf_sem_sim) / 2 clare_max_avg_go_mf_sem_sim,
(clare_max_2.go_slim_sem_sim + clare_max_1.go_slim_sem_sim) / 2 clare_max_avg_go_slim_sem_sim,
(clare_max_2.phylogenic_similarity + clare_max_1.phylogenic_similarity) / 2 clare_max_avg_phylogenic_similarity,
(clare_max_2.s_degree + clare_max_1.s_degree) / 2 clare_max_avg_s_degree,
(clare_max_2.s_clustering_coef + clare_max_1.s_clustering_coef) / 2 clare_max_avg_s_clustering_coef,
(clare_max_2.s_betweenness + clare_max_1.s_betweenness) / 2 clare_max_avg_s_betweenness,
(clare_max_2.s_closeness + clare_max_1.s_closeness) / 2 clare_max_avg_s_closeness,
(clare_max_2.s_neighbor_sharing + clare_max_1.s_neighbor_sharing) / 2 clare_max_avg_s_neighbor_sharing,
(clare_max_2.s_shortest_path_length + clare_max_1.s_shortest_path_length) / 2 clare_max_avg_s_shortest_path_length,
(clare_max_2.s_eb_max + clare_max_1.s_eb_max) / 2 clare_max_avg_s_eb_max,
(clare_max_2.s_eb_min + clare_max_1.s_eb_min) / 2 clare_max_avg_s_eb_min,
(clare_max_2.s_eb_mean + clare_max_1.s_eb_mean) / 2 clare_max_avg_s_eb_mean,
(clare_max_2.s_eb_fraction + clare_max_1.s_eb_fraction) / 2 clare_max_avg_s_eb_fraction,
(clare_max_2.s_number_of_shortest_paths + clare_max_1.s_number_of_shortest_paths) / 2 clare_max_avg_s_number_of_shortest_paths,
# clare_max_diff
(clare_max_2.bg_degree - clare_max_1.bg_degree) clare_max_diff_bg_degree,
(clare_max_2.bg_clustering_coef - clare_max_1.bg_clustering_coef) clare_max_diff_bg_clustering_coef,
(clare_max_2.bg_betweenness - clare_max_1.bg_betweenness) clare_max_diff_bg_betweenness,
(clare_max_2.bg_closeness - clare_max_1.bg_closeness) clare_max_diff_bg_closeness,
(clare_max_2.bg_neighbor_sharing - clare_max_1.bg_neighbor_sharing) clare_max_diff_bg_neighbor_sharing,
(clare_max_2.bg_shortest_path_length - clare_max_1.bg_shortest_path_length) clare_max_diff_bg_shortest_path_length,
(clare_max_2.bg_eb_max - clare_max_1.bg_eb_max) clare_max_diff_bg_eb_max,
(clare_max_2.bg_eb_min - clare_max_1.bg_eb_min) clare_max_diff_bg_eb_min,
(clare_max_2.bg_eb_mean - clare_max_1.bg_eb_mean) clare_max_diff_bg_eb_mean,
(clare_max_2.bg_eb_fraction - clare_max_1.bg_eb_fraction) clare_max_diff_bg_eb_fraction,
(clare_max_2.bg_number_of_shortest_paths - clare_max_1.bg_number_of_shortest_paths) clare_max_diff_bg_number_of_shortest_paths,
(clare_max_2.coexpression - clare_max_1.coexpression) clare_max_diff_coexpression,
(clare_max_2.gi_degree - clare_max_1.gi_degree) clare_max_diff_gi_degree,
(clare_max_2.gi_clustering_coef - clare_max_1.gi_clustering_coef) clare_max_diff_gi_clustering_coef,
(clare_max_2.gi_betweenness - clare_max_1.gi_betweenness) clare_max_diff_gi_betweenness,
(clare_max_2.gi_closeness - clare_max_1.gi_closeness) clare_max_diff_gi_closeness,
(clare_max_2.gi_neighbor_sharing - clare_max_1.gi_neighbor_sharing) clare_max_diff_gi_neighbor_sharing,
(clare_max_2.gi_shortest_path_length - clare_max_1.gi_shortest_path_length) clare_max_diff_gi_shortest_path_length,
(clare_max_2.gi_eb_max - clare_max_1.gi_eb_max) clare_max_diff_gi_eb_max,
(clare_max_2.gi_eb_min - clare_max_1.gi_eb_min) clare_max_diff_gi_eb_min,
(clare_max_2.gi_eb_mean - clare_max_1.gi_eb_mean) clare_max_diff_gi_eb_mean,
(clare_max_2.gi_eb_fraction - clare_max_1.gi_eb_fraction) clare_max_diff_gi_eb_fraction,
(clare_max_2.gi_number_of_shortest_paths - clare_max_1.gi_number_of_shortest_paths) clare_max_diff_gi_number_of_shortest_paths,
(clare_max_2.go_all_sem_sim - clare_max_1.go_all_sem_sim) clare_max_diff_go_all_sem_sim,
(clare_max_2.go_bp_sem_sim - clare_max_1.go_bp_sem_sim) clare_max_diff_go_bp_sem_sim,
(clare_max_2.go_cc_sem_sim - clare_max_1.go_cc_sem_sim) clare_max_diff_go_cc_sem_sim,
(clare_max_2.go_mf_sem_sim - clare_max_1.go_mf_sem_sim) clare_max_diff_go_mf_sem_sim,
(clare_max_2.go_slim_sem_sim - clare_max_1.go_slim_sem_sim) clare_max_diff_go_slim_sem_sim,
(clare_max_2.phylogenic_similarity - clare_max_1.phylogenic_similarity) clare_max_diff_phylogenic_similarity,
(clare_max_2.s_degree - clare_max_1.s_degree) clare_max_diff_s_degree,
(clare_max_2.s_clustering_coef - clare_max_1.s_clustering_coef) clare_max_diff_s_clustering_coef,
(clare_max_2.s_betweenness - clare_max_1.s_betweenness) clare_max_diff_s_betweenness,
(clare_max_2.s_closeness - clare_max_1.s_closeness) clare_max_diff_s_closeness,
(clare_max_2.s_neighbor_sharing - clare_max_1.s_neighbor_sharing) clare_max_diff_s_neighbor_sharing,
(clare_max_2.s_shortest_path_length - clare_max_1.s_shortest_path_length) clare_max_diff_s_shortest_path_length,
(clare_max_2.s_eb_max - clare_max_1.s_eb_max) clare_max_diff_s_eb_max,
(clare_max_2.s_eb_min - clare_max_1.s_eb_min) clare_max_diff_s_eb_min,
(clare_max_2.s_eb_mean - clare_max_1.s_eb_mean) clare_max_diff_s_eb_mean,
(clare_max_2.s_eb_fraction - clare_max_1.s_eb_fraction) clare_max_diff_s_eb_fraction,
(clare_max_2.s_number_of_shortest_paths - clare_max_1.s_number_of_shortest_paths) clare_max_diff_s_number_of_shortest_paths

FROM ALL_TRAINING_DATA_PAIR ap
JOIN ALL_TRAINING_DATA_PAIR_GBDPP ap_gbdpp USING (a_1, b_1, a_2, b_2)
JOIN ALL_TRAINING_DATA_PAIR_GBCLP ap_gbdcl USING (c_1, c_2)
# 1
JOIN ALL_TRAINING_DATA_GBDP a_gbdp_1 ON (a_gbdp_1.a = ap.a_1 and a_gbdp_1.b = ap.b_1)
JOIN ALL_TRAINING_DATA_GBDP a_gbdp_2 ON (a_gbdp_2.a = ap.a_2 and a_gbdp_2.b = ap.b_2)
# 2
JOIN ALL_TRAINING_DATA_GBCL a_gbcl_1 ON (a_gbcl_1.c = ap.c_1)
JOIN ALL_TRAINING_DATA_GBCL a_gbcl_2 ON (a_gbcl_2.c = ap.c_2)
# 3
LEFT JOIN original_target_features_avg clare_avg_1 ON (clare_avg_1.a = ap.a_1 and clare_avg_1.b = ap.b_1)
LEFT JOIN original_target_features_avg clare_avg_2 ON (clare_avg_2.a = ap.a_2 and clare_avg_2.b = ap.b_2)
# 4
LEFT JOIN original_target_features_max clare_max_1 ON (clare_max_1.a = ap.a_1 and clare_max_1.b = ap.b_1)
LEFT JOIN original_target_features_max clare_max_2 ON (clare_max_2.a = ap.a_2 and clare_max_2.b = ap.b_2)
# 5
# drug similarity
# 6
# coexpression
# 7
# Methylation
# where ap.synergy_score_diff IS NOT NULL
;
